const yesBtn = document.getElementById('yes-btn');
const noBtn = document.getElementById('no-btn');
const messageCard = document.getElementById('message-card');
const overlay = document.getElementById('overlay');
const unlockBtn = document.getElementById('unlock-btn');
const passwordInput = document.getElementById('password');
const lockScreen = document.getElementById('lock-screen');
const mainContent = document.getElementById('main-content');
const errorMsg = document.getElementById('error-msg');

const CORRECT_PASSWORD = "24022006";

// Password Unlock Logic
unlockBtn.addEventListener('click', checkPassword);
passwordInput.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') checkPassword();
});

function checkPassword() {
    if (passwordInput.value === CORRECT_PASSWORD) {
        lockScreen.style.display = 'none';
        mainContent.style.display = 'block';
        createHearts(); // Sprinkle some hearts on entry
    } else {
        errorMsg.style.display = 'block';
        passwordInput.style.borderColor = '#ff4d4d';
        setTimeout(() => {
            errorMsg.style.display = 'none';
            passwordInput.style.borderColor = 'var(--soft-mint)';
        }, 2000);
    }
}

// Function to move the "No" button
noBtn.addEventListener('mouseover', moveButton);
noBtn.addEventListener('touchstart', (e) => {
    e.preventDefault(); // Prevent accidental clicks on mobile
    moveButton();
});

function moveButton() {
    // Calculate safe boundaries
    const padding = 20;
    const maxX = window.innerWidth - noBtn.offsetWidth - padding;
    const maxY = window.innerHeight - noBtn.offsetHeight - padding;

    const x = Math.max(padding, Math.random() * maxX);
    const y = Math.max(padding, Math.random() * maxY);

    noBtn.style.position = 'fixed';
    noBtn.style.left = `${x}px`;
    noBtn.style.top = `${y}px`;
    noBtn.style.zIndex = '1000';
}

// "No" button click (for mobile or if they manage to click it)
noBtn.addEventListener('click', () => {
    alert("Hey! You're not supposed to be able to click this! 😤 Please forgive me!");
});

// Function to handle "Yes" click
yesBtn.addEventListener('click', () => {
    createHearts();
    setTimeout(() => {
        messageCard.classList.add('active');
        overlay.classList.add('active');
    }, 500);
});

function closeMessage() {
    messageCard.classList.remove('active');
    overlay.classList.remove('active');
}

// Reasons Logic
const reasons = [
    "You're the first person I want to tell everything to.",
    "You left your cricket match just to see me! 🏏❤️",
    "You always know when I'm not feeling okay.",
    "Your laugh is literally my favorite sound.",
    "You're the most loyal friend someone could ask for.",
    "You put up with my mood swings without a word.",
    "You always take my side (even when I'm a bit wrong).",
    "You're actually a very good listener.",
    "You remember the small details I tell you.",
    "You make even boring days feel fun.",
    "Your sense of humor is top-tier (mostly).",
    "You're one of the few people who 'gets' me.",
    "You give the best advice when I'm stressed.",
    "You're genuinely a kind-hearted person.",
    "You don't judge me for my weird habits.",
    "You make me feel safe being myself.",
    "The way you get excited about things you love.",
    "You're incredibly patient with me.",
    "You're always there with a text when I need one.",
    "You're my favorite person to annoy.",
    "Our inside jokes that no one else understands.",
    "You're more like family than just a friend.",
    "You're genuinely proud of my achievements.",
    "You can tell what I'm thinking just by a look.",
    "You're honest with me even when it's hard.",
    "You have a heart of gold.",
    "The way you handle my drama so calmly.",
    "You're my go-to person for everything.",
    "You make me a better person.",
    "I can trust you with any secret.",
    "You're always down for random plans.",
    "You're the person I can be silent with comfortably.",
    "You always find a way to cheer me up.",
    "You're more than just a best friend, you're a support system.",
    "You actually care about how my day went.",
    "You're one of the strongest people I know.",
    "You're weird, and I love that about you.",
    "You never give up on people you care about.",
    "You're incredibly humble.",
    "You're my favorite person to share music with.",
    "You've seen me at my worst and stayed.",
    "You always know how to calm me down.",
    "You're the best person to waste time with.",
    "You have a very calming presence.",
    "You're always ready to help anyone in need.",
    "You're genuinely one of a kind.",
    "You make me feel like I matter.",
    "You're the best teammate for anything.",
    "The way you standing up for what's right.",
    "You're my favorite human being, period.",
    "You're always honest about your feelings.",
    "You're a very good judge of character.",
    "You have a great taste in almost everything.",
    "You're incredibly supportive of my dreams.",
    "I love how we can talk for hours about nothing.",
    "You're my favorite person to get food with.",
    "You're always there to humble me when I need it.",
    "You're a very genuine soul.",
    "You're basically my human diary.",
    "You make me feel heard.",
    "You're always willing to learn and grow.",
    "The way you protect the people you love.",
    "You're my comfort person.",
    "I love how you always find the silver lining.",
    "You're very observant.",
    "You're the most reliable person I know.",
    "You have a very contagious energy.",
    "You're the only one who can handle my sarcasm.",
    "You're always there to remind me of my worth.",
    "You're a really good influence on me.",
    "You're never too busy for me.",
    "I love our late-night deep conversations.",
    "You're very thoughtful in your actions.",
    "You're my biggest cheerleader.",
    "You're very selfless when it comes to friends.",
    "I love your random observations about life.",
    "You're the person I want to travel the world with.",
    "You're very forgiving (I hope!).",
    "You're a constant in my ever-changing life.",
    "You're the person I feel most 'regular' with.",
    "You're very grounded.",
    "I love how you're not afraid to be yourself.",
    "You're a really good problem solver.",
    "You're my favorite person to rant to.",
    "You're very protective of our friendship.",
    "You're always there to catch me if I fall.",
    "You're my partner in crime.",
    "I love how you always keep your promises.",
    "You're very intuitive.",
    "You're the 'calm' to my 'storm'.",
    "You're my favorite reason to smile.",
    "You're very easy to talk to.",
    "You're my safest place.",
    "I love how we can communicate without words.",
    "You're a true gem of a person.",
    "You're my constant source of happiness.",
    "You're the best thing that ever happened to me.",
    "You're my forever friend.",
    "I simply love you for who you are.",
    "One argument could never change how much you mean to me.",
    "Your presence makes everything better.",
    "You're the person I can always count on.",
    "You're my favorite traveling companion.",
    "You're the best listener in the world.",
    "You have the kindest soul I've ever met.",
    "You're my partner in all my adventures.",
    "I love how we can talk about nothing for hours.",
    "You're my rock when things get tough.",
    "You're the first person I want to share good news with.",
    "You're my favorite person to watch movies with.",
    "You're simply irreplaceable.",
    "You're the best best friend anyone could wish for.",
    "I trust you more than anyone else.",
    "You're my favorite human.",
    "You're the peanut butter to my jelly.",
    "We're basically a two-person cult.",
    "You're my soulmate in friend form.",
    "I'm so lucky to have you in my life.",
    "You're my sunshine on a cloudy day.",
    "You're the only one who truly understands my silence.",
    "You're my constant in a world of variables.",
    "You're the best version of a human being.",
    "I love you more than words can say (as a bestie!).",
    "You're the peace in my chaotic life.",
    "You're the person I can always be 'ugly-funny' with.",
    "I love how we can have a whole conversation with just facial expressions.",
    "You're my favorite person to share a sunset (or a match) with.",
    "You're the only one who knows my true favorite song.",
    "You make me feel like I can take on the world.",
    "You're my favorite human notification. 📱✨",
    "I love how we share the same brain cell sometimes.",
    "You're the best person to have a deep conversation with at 3 AM.",
    "You're the person I'd choose to be stranded on an island with.",
    "You always respect my boundaries without me having to explain them twice.",
    "The way you remember my coffee/tea order perfectly.",
    "You never make me feel like I'm asking for too much.",
    "You're the only person who can make me laugh when I'm actually crying.",
    "I love how you get so focused when you're working on something you're passionate about.",
    "You're incredibly patient even when I'm being difficult.",
    "The way you defend me when people talk behind my back.",
    "You're the first person I want to call when I see something funny.",
    "You've taught me how to be more kind to myself.",
    "I love the way you look when you're genuinely surprised.",
    "You're the best at giving 'real' talk when I need it most.",
    "You never let me give up on myself.",
    "I love how you always find the perfect meme for every situation.",
    "You make me feel like I'm the most important person in the room.",
    "You're so thoughtful with your gifts, no matter how small they are.",
    "I love how you can admit when you're wrong.",
    "You're the only one who knows my 'secret' playlist.",
    "The way you handle stress with so much grace.",
    "You always make sure I've eaten and had enough water.",
    "I love our shared love for random documentaries.",
    "You're the person I feel most comfortable being quiet with.",
    "You never judging my taste in movies.",
    "The way you always walk on the outside of the sidewalk to protect me.",
    "You're so good at giving credit where it's due.",
    "I love how you celebrate my small wins as if they were your own.",
    "You're the only one who knows how to calm my anxiety.",
    "The way you explain things without ever sounding condescending.",
    "I love how you're not afraid to show your vulnerable side.",
    "You're such a good role model for those around you.",
    "The way you can turn any bad day around with just a text.",
    "I love how you're always willing to try new things with me.",
    "You're the most reliable person I've ever met.",
    "The way you always keep your word.",
    "I love how you never make me feel guilty for needing space.",
    "You're such a great storyteller.",
    "The way you always make sure everyone feels included.",
    "I love your dedication to your goals.",
    "You're so much smarter than you give yourself credit for.",
    "The way you notice when I've changed something subtle about my appearance.",
    "I love how we can talk about the universe and then immediately talk about pizza.",
    "You're the best at keeping secrets.",
    "The way you handle disappointment with such maturity.",
    "I love how you always know exactly what to say to make me feel better.",
    "You're such a good influence on everyone you meet.",
    "The way you're so protective of the people you care about.",
    "I love how you never take things for granted.",
    "You're so generous with your time and energy.",
    "The way you can find a solution to almost any problem.",
    "I love how you're always looking for ways to improve yourself.",
    "You're simply the best person I know.",
    "The way you value our friendship more than anything else.",
    "I love how you're always there to listen to my rants.",
    "You're so good at making people feel heard.",
    "The way you always find a way to make me smile.",
    "I love how you're so unapologetically yourself.",
    "You're such a great teammate in every sense of the word.",
    "The way you always go above and beyond for others.",
    "I love how you're always there to offer a helping hand.",
    "You're so insightful and wise.",
    "The way you always stay true to your values.",
    "I love how you're always there to support my crazy ideas.",
    "You're so good at finding the beauty in the mundane.",
    "The way you always treat everyone with respect.",
    "I love how you're always there to cheer me on.",
    "You're such a positive force in my life.",
    "The way you always find a way to make things work.",
    "I love how you're so thoughtful and considerate.",
    "You're such a great friend and an even better person.",
    "The way you always make me feel loved and appreciated.",
    "I love how you're always there to share a laugh with me.",
    "You're so kind and compassionate.",
    "The way you always find a way to brighten my day.",
    "I love how you're always there to lend an ear.",
    "You're such a supportive and caring person.",
    "The way you always find a way to make me feel special.",
    "I love how you're always there to share a moment with me.",
    "You're so honest and trustworthy.",
    "The way you always find a way to make me feel happy.",
    "I love how you're always there to give me a hug (metaphorically or literally).",
    "You're such a wonderful person inside and out.",
    "The way you always find a way to make me feel at home.",
    "I love how you're always there to share a dream with me.",
    "You're so inspiring and motivating.",
    "The way you always find a way to make me feel proud.",
    "I love how you're always there to share a secret with me.",
    "You're so dependable and constant.",
    "The way you always find a way to make me feel safe.",
    "I love how you're always there to share a story with me.",
    "You're so humble and down-to-earth.",
    "The way you always find a way to make me feel understood.",
    "I love how you're always there to share a smile with me.",
    "You're so brave and courageous.",
    "The way you always find a way to make me feel valued.",
    "I love how you're always there to share a thought with me.",
    "You're so selfless and giving.",
    "The way you always find a way to make me feel worthy.",
    "I love how you're always there to share a vision with me.",
    "You're so talented and gifted.",
    "The way you always find a way to make me feel alive.",
    "I love how you're always there to share a wonder with me.",
    "You're so unique and special.",
    "The way you always find a way to make me feel bold.",
    "I love how you're always there to share a zest with me.",
    "You're so amazing and incredible.",
    "The way you always find a way to make me feel calm.",
    "I love how you're always there to share a peace with me.",
    "You're so beautiful and radiant.",
    "The way you always find a way to make me feel bright.",
    "I love how you're always there to share a glow with me.",
    "You're so charming and delightful.",
    "The way you always find a way to make me feel cheerful.",
    "I love how you're always there to share a joy with me.",
    "You're so elegant and graceful.",
    "The way you always find a way to make me feel light.",
    "I love how you're always there to share a breath with me.",
    "You're so fascinating and intriguing.",
    "The way you always find a way to make me feel curious.",
    "I love how you're always there to share a discovery with me.",
    "You're so magnificent and splendid.",
    "The way you always find a way to make me feel grand.",
    "I love how you're always there to share a dreamscape with me.",
    "You're so precious and dear.",
    "The way you always find a way to make me feel cherished.",
    "I love how you're always there to share a heartbeat with me.",
    "You're so remarkable and extraordinary.",
    "I love how you're always there to share a lifetime with me.",
    "You're so terrific and wonderful.",
    "I love how you're always there to share a world with me.",
    "You're so viliant and strong.",
    "The way you always find a way to make me feel protected.",
    "I love how you're always there to share a shield with me.",
    "You're so wise and knowing.",
    "The way you always find a way to make me feel smart.",
    "I love how you're always there to share a lesson with me.",
    "You're so youthful and spirited.",
    "The way you always find a way to make me feel young at heart.",
    "I love how you're always there to share a memory with me.",
    "You're so zealous and passionate.",
    "The way you always find a way to make me feel excited.",
    "I love how you're always there to share an adventure with me.",
    "You're so authentic and real.",
    "The way you always find a way to make me feel grounded.",
    "I love how you're always there to share a truth with me.",
    "You're so compassionate and kind.",
    "The way you always find a way to make me feel loved.",
    "I love how you're always there to share a kindness with me.",
    "You're so determined and focused.",
    "The way you always find a way to make me feel capable.",
    "I love how you're always there to share a goal with me.",
    "You're experience and knowledge.",
    "The way you always find a way to make me feel experienced.",
    "I love how you're always there to share a path with me.",
    "You're so friendly and outgoing.",
    "The way you always find a way to make me feel welcome.",
    "I love how you're always there to share a friend with me.",
    "You're so generous and giving.",
    "The way you always find a way to make me feel provided for.",
    "I love how you're always there to share a gift with me.",
    "You're so hardworking and diligent.",
    "The way you always find a way to make me feel successful.",
    "I love how you're always there to share a victory with me.",
    "You're so imaginative and creative.",
    "The way you always find a way to make me feel inspired.",
    "I love how you're always there to share a creation with me.",
    "You're so joyful and happy.",
    "The way you always find a way to make me feel joyful.",
    "You're so knowledgeable and smart.",
    "The way you always find a way to make me feel informed.",
    "I love how you're always there to share a fact with me.",
    "You're so loving and caring.",
    "The way you always find a way to make me feel cared for.",
    "I love how you're always there to share a love with me.",
    "You're so modest and humble.",
    "The way you always find a way to make me feel humble.",
    "I love how you're always there to share a humility with me.",
    "You're so noble and honorable.",
    "The way you always find a way to make me feel honored.",
    "I love how you're always there to share an honor with me.",
    "You're so optimistic and positive.",
    "The way you always find a way to make me feel hopeful.",
    "I love how you're always there to share a hope with me.",
    "You're so patient and kind.",
    "The way you always find a way to make me feel at peace.",
    "I love how you're always there to share a patience with me.",
    "You're so quiet and thoughtful.",
    "The way you always find a way to make me feel heard.",
    "I love how you're always there to share a silence with me.",
    "You're so reliable and trustworthy.",
    "I love how you're always there to share a trust with me.",
    "You're so sincere and honest.",
    "The way you always find a way to make me feel honest.",
    "I love how you're always there to share a sincerity with me.",
    "You're so thoughtful and kind.",
    "The way you always find a way to make me feel thought of.",
    "You're so understanding and empathetic.",
    "I love how you're always there to share a feeling with me.",
    "You're so vibrant and alive.",
    "I love how you're always there to share a vibe with me.",
    "The way you always find a way to make me feel wise.",
    "I love how you're always there to share a wisdom with me.",
    "You're so xenial and hospitable.",
    "I love how you're always there to share a home with me.",
    "You're so youthful and energetic.",
    "The way you always find a way to make me feel young.",
    "I love how you're always there to share a youth with me.",
    "You're so zealous and enthusiastic.",
    "I love how you're always there to share a zeal with me.",
    "You're my partner in every crime.",
    "You're the person I can always talk to.",
    "You're the person I can always trust.",
    "You're the person I can always rely on.",
    "You're the person I can always love.",
    "You're the person I can always be with.",
    "You're the person I can always share with.",
    "You're the person I can always hear.",
    "You're the person I can always see.",
    "You're the person I can always feel.",
    "You're the person I can always know.",
    "You're the person I can always understand.",
    "You're the person I can always appreciate.",
    "You're the person I can always admire.",
    "You're the person I can always respect.",
    "You're the person I can always value.",
    "You're the person I can always cherish.",
    "You're the person I can always adore.",
    "You're the person I can always treasure.",
    "You're the person I can always believe in.",
    "You're the person I can always support.",
    "You're the person I can always encourage.",
    "You're the person I can always inspire.",
    "You're the person I can always motivate.",
    "You're the person I can always cheer for.",
    "You're the person I can always celebrate.",
    "You're the person I can always honor.",
    "You're the person I can always be proud of.",
    "You're the person I can always depend on.",
    "You're the person I can always be safe with.",
    "You're the person I can always be happy with.",
    "You're the person I can always be kind to.",
    "You're the person I can always be honest with.",
    "You're the person I can always be real with.",
    "You're the person I can always be me with.",
    "You're the person I can always be one with.",
    "You're the person I can always be together with.",
    "You're the person I can always be forever with.",
    "You're the person I can always be a friend with.",
    "You're the person I can always be a bestie with.",
    "You're the person I can always be a partner with.",
    "You're the person I can always be a soulmate with.",
    "You're the person I can always be a family with.",
    "You're the person I can always be a legend with.",
    "You're the person I can always be a star with.",
    "You're the person I can always be a light with.",
    "You're the person I can always be a dream with.",
    "You're the person I can always be a world with.",
    "You're the person I can always be a universe with.",
    "You're the person I can always be everything with.",
    "The way you always text 'home safe?' without me asking.",
    "You're the only one who can talk me out of a bad decision.",
    "I love how you actually read the long articles I send you.",
    "The way you always know when I need a hug but I'm too shy to ask.",
    "You're the best person to go on a long drive with.",
    "I love how you always have a weird fun fact ready.",
    "The way you look when you're deeply concentrated on a game.",
    "You're the only one who can finish my sentences correctly.",
    "I love how you never make fun of my niche interests.",
    "The way you always make sure there's a seat for me.",
    "You're the best person to share a dessert with.",
    "I love how you remember my favorite childhood stories.",
    "The way you handle spicy food like a pro (or pretend to).",
    "You're the only one who gets my extremely specific movie references.",
    "I love how you always remind me to take a break when I'm working too hard.",
    "The way you look at me when you're about to tell a joke.",
    "You're the best person to have a debate with because you actually listen.",
    "I love how you're always down for a spontaneous bookstore trip.",
    "The way you always know which song will make me feel better.",
    "You're the only one who knows my true 'introvert' battery level.",
    "I love how you always help me see the other side of an argument.",
    "The way you always make sure I feel included in group conversations.",
    "You're the best person to watch a scary movie with (even if we both hide).",
    "I love how you always notice the little things I do for you.",
    "The way you always find the best gifts that aren't even expensive.",
    "You're the only one who knows my real 'vibe' at any given moment.",
    "I love how you're always patient when I'm rambling about nothing.",
    "The way you always make sure I'm comfortable in new places.",
    "You're the best person to have a deep talk with at a party.",
    "I love how you always encourage me to stand up for myself.",
    "The way you always know when I'm just 'acting' okay.",
    "You're the only one who can make a rainy day feel productive.",
    "I love how you always check in on me after a long day.",
    "The way you always help me organize my thoughts.",
    "You're the best person to share a secret snack with.",
    "I love how you always support my weird fashion choices.",
    "The way you always know which meme will make me cry-laugh.",
    "You're the only one who treats my problems like they're yours too.",
    "I love how you always find a way to make chores feel fun.",
    "The way you always look so proud when I achieve something.",
    "You're the best person to get lost with in a new city.",
    "I love how you always apologize first when we have a silly tiff.",
    "The way you always know when I need a distraction.",
    "You're the only one who understands my 'coded' texts.",
    "I love how you always motivate me to go to the gym (even when I hate it).",
    "The way you always make sure I don't feel lonely in a crowd.",
    "You're the best person to gossip with because you're actually fair.",
    "I love how you always remember the dates of things that matter to me.",
    "The way you always make sure my phone is charged or I have a charger.",
    "You're the only one who can make me feel like a kid again.",
    "I love how you always stay calm when I'm panicking.",
    "The way you always know exactly which snacks to buy.",
    "You're the best person to have a movie marathon with.",
    "I love how you always listen to my 10-minute voice notes.",
    "The way you always make sure I'm not overthinking things.",
    "You're the only one who knows my real coffee-to-milk ratio.",
    "I love how you always support my side hustle or hobbies.",
    "The way you always know when I need a change of scenery.",
    "You're the best person to go to a museum with.",
    "I love how you always help me find my keys (and my sanity).",
    "The way you always know which funny video will cheer me up.",
    "You're the only one who knows my 'social' battery is low before I do.",
    "I love how you always defend my choices to others.",
    "The way you always make sure I have the best seat in the house.",
    "You're the best person to have a late-night talk with on the balcony.",
    "I love how you always notice when I've had a breakthrough.",
    "The way you always make sure I'm hydrated.",
    "You're the only one who can make a long line feel short.",
    "I love how you always share your fries with me.",
    "The way you always know when I need a pep talk.",
    "You're the best person to take a nap near.",
    "I love how you always remember my favorite book characters.",
    "The way you always make sure I feel safe walking to my car.",
    "You're the only one who knows my real 'angry' face vs my 'bored' face.",
    "I love how you always encourage my creative side.",
    "The way you always know when I need a good cry and a movie.",
    "You're the best person to have a zero-context conversation with.",
    "I love how you always believe in my potential even when I don't.",
    "The way you always make sure I'm not being too hard on myself.",
    "You're the only one who can make a boring meeting feel like a comedy show.",
    "I love how you always share your music discoveries with me.",
    "The way you always know when I need a digital detox.",
    "You're the best person to go to a concert with.",
    "I love how you always help me see the silver lining in every failure.",
    "The way you always make sure I'm taking care of my health.",
    "You're the only one who knows my 'true' laugh (the one with the snort).",
    "I love how you always support my random 2 AM ideas.",
    "The way you always know when I need a quiet night in.",
    "You're the best person to share a life plan with.",
    "I love how you always remember the lyrics to our favorite songs.",
    "The way you always make sure I don't feel forgotten.",
    "You're the only one who can make me feel like I can fly.",
    "I love how you always celebrate 'anniversaries' of small things.",
    "The way you always know when I need a change of pace.",
    "You're the best person to have a deep dive into a conspiracy theory with.",
    "I love how you always notice when I'm being too self-critical.",
    "The way you always make sure I'm wearing enough layers when it's cold.",
    "You're the only one who knows my 'hidden' talents.",
    "I love how you always help me navigate difficult conversations.",
    "The way you always know when I need a sweet treat.",
    "You're the best person to go to a thrift store with.",
    "I love how you always support my thirst for knowledge.",
    "The way you always make sure I'm not feeling left out.",
    "You're the only one who can make a bad haircut feel like a fashion statement.",
    "I love how you always share your snacks without being asked.",
    "The way you always know when I need a motivational quote.",
    "You're the best person to have a 'do nothing' day with.",
    "I love how you always remember the name of that one actor I like.",
    "The way you always make sure I feel like I'm part of the team.",
    "You're the only one who can make a long commute feel like an adventure.",
    "I love how you always support my growth as a person.",
    "The way you always know when I'm just 'over it'.",
    "You're the best person to have a deep conversation about life with.",
    "I love how you always notice when I've done something nice for myself.",
    "The way you always make sure I'm not sacrificing my happiness.",
    "You're the only one who knows my 'real' opinion on things.",
    "I love how you always share your joy with me.",
    "The way you always know when I need a hug and a pizza.",
    "You're the best person to have a 'new hobby' phase with.",
    "I love how you always remember the little things that make me happy.",
    "The way you always make sure I feel like I'm enough.",
    "You're the only one who can make a stressful day feel like a breeze.",
    "I love how you always support my dreams, no matter how big.",
    "The way you always know when I need a quiet moment.",
    "You're the best person to have a 'bad day' debrief with.",
    "I love how you always notice when I'm being brave.",
    "The way you always make sure I'm not feeling overwhelmed.",
    "You're the only one who can make me feel like a superstar.",
    "I love how you always share your life with me.",
    "The way you always know when I need a laugh and a drink (water/juice!).",
    "You're the best person to have a 'future self' conversation with.",
    "I love how you always remember my favorite flowers.",
    "The way you always make sure I'm not feeling invisible.",
    "You're the only one who can make a simple walk feel like a journey.",
    "I love how you always support my mental health.",
    "The way you always know when I need a break from social media.",
    "You're the best person to have a 'dream life' conversation with.",
    "I love how you always notice when I'm making progress.",
    "The way you always make sure I'm not feeling alone in my thoughts.",
    "You're the only one who can make me feel like everything is possible.",
    "I love how you always share your light with me.",
    "The way you always know when I need a smile and a story.",
    "You're the best person to have a 'real talk' with.",
    "I love how you always remember the details of our first meeting.",
    "The way you always make sure I'm not feeling disconnected.",
    "You're the only one who can make a quiet room feel full.",
    "I love how you always support my journey to find myself.",
    "The way you always know when I need a spark of inspiration.",
    "You're the best person to have a 'what if' conversation with.",
    "I love how you always notice when I'm being kind to others.",
    "The way you always make sure I'm not feeling misunderstood.",
    "You're the only one who can make me feel like I belong.",
    "I love how you always share your wisdom with me.",
    "The way you always know when I need a hand and a hope.",
    "You're the best person to have a 'deep soul' conversation with.",
    "I love how you always remember to check in on me when I'm sick.",
    "The way you always make sure I'm not feeling lost.",
    "You're the only one who can make a dark day feel bright.",
    "I love how you always support my choices for my future.",
    "The way you always know when I need a reminder of my strength.",
    "You're the best person to have a 'soulmates' talk with.",
    "I love how you always notice when I'm being strong.",
    "The way you always make sure I'm not feeling forgotten by time.",
    "You're the only one who can make me feel like a hero in my own story.",
    "I love how you always share your heart with me.",
    "The way you always know when I need a peace and a purpose.",
    "You're the best person to have a 'forever friends' talk with.",
    "I love how you always remember the lyrics to 'our' song.",
    "The way you always make sure I'm not feeling small.",
    "You're the only one who can make me feel like a giant.",
    "I love how you always support my path to happiness.",
    "The way you always know when I need a bit of magic.",
    "You're the best person to have a 'life goals' talk with.",
    "I love how you always notice when I'm being selfless.",
    "The way you always make sure I'm not feeling like a burden.",
    "You're the only one who can make me feel like a blessing.",
    "I love how you always share your path with me.",
    "The way you always know when I need a bit of wonder.",
    "You're the best person to have a 'cosmic' talk with.",
    "I love how you always remember the name of my favorite pet.",
    "The way you always make sure I'm not feeling like a ghost.",
    "You're the only one who can make me feel so alive.",
    "I love how you always support my need for adventure.",
    "The way you always know when I need a bit of grit.",
    "You're the best person to have a 'starlight' talk with.",
    "I love how you always notice when I'm being authentic.",
    "The way you always make sure I'm not feeling like a number.",
    "You're the only one who can make me feel like a legend.",
    "I love how you always share your world with me.",
    "The way you always know when I need a bit of grace.",
    "You're the best person to have a 'timeless' talk with.",
    "I love how you always remember the way I like my pizza.",
    "The way you always make sure I'm not feeling like a stranger.",
    "You're the only one who can make me feel like I'm home.",
    "I love how you always support my need for silence.",
    "The way you always know when I need a bit of fire.",
    "You're the best person to have a 'soul' talk with.",
    "The way you always make sure I'm not feeling like an echo.",
    "You're the only one who can make me feel like a voice.",
    "I love how you always share your soul with me.",
    "The way you always know when I need a bit of light.",
    "You're the best person to have a 'human' talk with.",
    "I love how you always remember the way I laugh.",
    "The way you always make sure I'm not feeling like a shadow.",
    "You're the only one who can make me feel like a light.",
    "I love how you always support my need for chaos (the good kind).",
    "The way you always know when I need a bit of calm.",
    "You're the best person to have a 'meaning of life' talk with.",
    "I love how you always notice when I'm being me.",
    "The way you always make sure I'm not feeling like a secret.",
    "You're the only one who can make me feel like a truth.",
    "I love how you always share your everything with me.",
    "The way you always know when I need a bit of 'you'.",
    "You're the first person I think of when I wake up.",
    "I love how you can solve a Rubik's cube (or try to!).",
    "You're the best person to play board games with.",
    "I love how you get so intense during a match.",
    "The way you always make sure my seat is adjusted right.",
    "You're the only one who knows my 'tells' when I'm lying.",
    "I love how you always encourage me to try that weird food.",
    "The way you look when you're thinking hard about a puzzle.",
    "You're the best person to go to a fair with.",
    "I love how you always remember to water the plants when I forget.",
    "The way you always know which font looks best for my projects.",
    "You're the only one who knows my 'true' favorite color is actually a specific shade.",
    "I love how you always help me with my technical issues.",
    "The way you always make sure I don't miss my flight/train.",
    "You're the best person to have a '90s nostalgia' night with.",
    "I love how you always notice the constellations when we're out.",
    "The way you always make sure I have enough storage on my phone.",
    "You're the only one who knows my real 'sleep' schedule.",
    "I love how you always support my hobby for collecting random things.",
    "You're the best person to have a 'cooking experiment' with.",
    "I love how you always remember my password when I forget it (safely!).",
    "The way you always make sure I'm not walking alone at night.",
    "You're the only one who can make me feel like a genius.",
    "I love how you always share your umbrella with me.",
    "The way you always know when I need a bit of structure.",
    "You're the best person to have a 'productive' Sunday with.",
    "I love how you always notice when I've cleaned my room.",
    "The way you always make sure I'm not overspending.",
    "You're the only one who knows my 'guilty pleasure' shows.",
    "The way you never judge my strange Spotify Wrapped.",
    "Your ability to make even a grocery run feel like an adventure.",
    "The way you listen to me talk about things you have no interest in.",
    "How you always know when I've had a bad day without me saying a word.",
    "The way you defend my name when I'm not in the room.",
    "Your incredibly contagious energy that brightens any room.",
    "The way you never make me feel guilty for needing a 'rotting day'.",
    "How you remember the names of my favorite childhood characters.",
    "The way you always pick up on my smallest mood shifts.",
    "Your patience when I'm trying to explain something and getting it all mixed up.",
    "The way you never make fun of my niche hobbies.",
    "How you always make sure I've reached home safely.",
    "The way you celebrate my tiny achievements like they're huge milestones.",
    "Your willingness to try my weird food experiments.",
    "The way you always know the exact meme to send to make me laugh.",
    "How you never make me feel like I'm taking up too much space.",
    "The way you give the most honest advice even when it's hard to hear.",
    "Your ability to stay calm when I'm spiraling.",
    "The way you look when you're genuinely excited about a cricket match.",
    "How you always remember my 'trigger' words or topics.",
    "The way you never force me to be social when my battery is low.",
    "Your respect for my quiet moments.",
    "The way you always help me see the logic when I'm overthinking.",
    "How you never make me feel 'too much' or 'not enough'.",
    "The way you always notice when I've changed my hair or outfit.",
    "Your commitment to being a better person every day.",
    "The way you handle difficult people with so much grace.",
    "How you always make me feel included in group settings.",
    "The way you never bring up my past mistakes to win an argument.",
    "Your ability to admit when you're wrong and apologize sincerely.",
    "The way you value my opinion on things that matter to you.",
    "How you always check if I'm comfortable in new environments.",
    "The way you remember the dates of things that I care about.",
    "Your genuine curiosity about the things I love.",
    "The way you never make me feel like I'm a burden.",
    "How you always find the silver lining in every disaster.",
    "The way you protect my peace as much as your own.",
    "Your ability to make me feel beautiful even on my worst days.",
    "The way you handle my drama without making me feel dramatic.",
    "How you always offer a helping hand before I even have to ask.",
    "The way you look at the stars with so much wonder.",
    "Your dedication to your friends and family.",
    "The way you never take our friendship for granted.",
    "How you're always willing to learn and unlearn things for me.",
    "The way you make 'doing nothing' feel like 'doing everything'.",
    "Your strength of character in the face of adversity.",
    "The way you never let a day go by without checking in.",
    "How you always make me feel like I can conquer the world.",
    "The way you speak about your dreams with so much passion.",
    "Your kindness toward strangers and animals.",
    "The way you never make me feel like I'm a second choice.",
    "How you always know when I just need a distraction.",
    "The way you listen to my 10-minute voice notes without complaining.",
    "Your ability to keep my secrets as if they were your own.",
    "The way you never mock my fears, no matter how irrational they are.",
    "How you always find the right words to settle my mind.",
    "The way you look when you're trying not to laugh at a serious moment.",
    "Your humility even when you've achieved something great.",
    "The way you always make sure I've eaten and slept well.",
    "How you never allow me to talk down to myself.",
    "The way you've seen me at my absolute lowest and still stayed.",
    "Your consistency in a world where everyone is temporary.",
    "The way you always respect my no without questioning it.",
    "How you always make me feel heard in a world that's so loud.",
    "The way you share your favorite books and music with me.",
    "Your ability to make a boring movie feel like a masterpiece with your commentary.",
    "The way you never let me go to sleep feeling upset with you.",
    "How you always prioritize our friendship over your ego.",
    "The way you look when you're lost in thought.",
    "Your sense of adventure that pushes me out of my comfort zone.",
    "How you never make me feel like I'm hard to love.",
    "The way you always choose me, every single day.",
    "Your ability to make me smile with just a look.",
    "The way you've become my safest place in this chaotic world.",
    "How you always remind me of my worth when I forget.",
    "The way you're genuinely happy for my success.",
    "Your ability to handle my mood swings with so much patience.",
    "The way you always make sure I'm hydrated (the water police!).",
    "How you never judge my order when we go out for food.",
    "The way you look when you're sleepily saying goodnight.",
    "Your belief in me even when I've lost belief in myself.",
    "The way you always find the perfect song for our drives.",
    "How you never make me feel like I'm too sensitive.",
    "The way you always know when I need a hug.",
    "Your ability to make me feel like I'm the only person who matters.",
    "The way you always keep your promises, no matter how small.",
    "How you never let me face my problems alone.",
    "The way you look when you're genuinely surprised by a gift.",
    "Your ability to make me laugh until my stomach hurts.",
    "The way you've become the sibling I never had.",
    "How you always make sure I'm taking care of my mental health.",
    "The way you respect my boundaries even during an argument.",
    "Your willingness to apologize even when it wasn't your fault.",
    "How you never make me feel like I'm an afterthought.",
    "The way you've taught me how to trust again.",
    "Your ability to see the best in people even when they don't see it themselves.",
    "The way you always make me feel protected.",
    "How you're the first person I want to tell everything to.",
    "The way you never make me feel like I have to change for you.",
    "Your ability to make me feel like I'm home.",
    "The way you always notice the little things I do for you.",
    "How you never make me feel like I'm asking for too much.",
    "Your dedication to making our friendship stronger.",
    "The way you look at me with so much kindness.",
    "How you always make me feel like I'm enough.",
    "The way you've become my favorite human being.",
    "Your ability to make me feel seen.",
    "The way you always choose to be kind.",
    "How you never let me feel like I'm alone.",
    "The way you've changed my life for the better.",
    "Your ability to make me feel lucky.",
    "The way you always find a way to make me laugh.",
    "How you're the best part of my day.",
    "The way you never give up on us.",
    "Your ability to make me feel proud.",
    "How you're simply irreplaceable.",
    "The way you've become my everything.",
    "Your ability to make me feel loved.",
    "The way you always choose us.",
    "How you're my favorite person to talk to.",
    "The way you never fail to make me happy.",
    "Your ability to make me feel special.",
    "The way you always find a way to make it right.",
    "How you're the light in my dark days.",
    "The way you've become my forever.",
    "Your ability to make me feel safe.",
    "How you're my favorite reason to smile.",
    "The way you never make me feel small.",
    "Your ability to make me feel important.",
    "The way you always find a way to stay.",
    "How you're my best friend in the whole world.",
    "The way you've become my home.",
    "Your ability to make me feel understood.",
    "The way you always find a way to care.",
    "How you're the best thing that ever happened to me.",
    "The way you never make me feel like I'm a mistake.",
    "Your ability to make me feel worthy.",
    "The way you always find a way to love.",
    "How you're my favorite person to be with.",
    "The way you never let me down.",
    "Your ability to make me feel good.",
    "The way you always find a way to help.",
    "How you're the only one who truly gets me.",
    "The way you've become my soulmate (in friend form!).",
    "Your ability to make me feel alive.",
    "The way you always find a way to be there.",
    "How you're the center of my universe.",
    "The way you never make me feel invisible.",
    "Your ability to make me feel visible.",
    "The way you always find a way to listen.",
    "How you're my favorite person to listen to.",
    "The way you never make me feel like I'm a bother.",
    "Your ability to make me feel wanted.",
    "The way you always find a way to choose me.",
    "How you're the one who makes it all okay.",
    "The way you've become my peace.",
    "Your ability to make me feel calm.",
    "The way you always find a way to be kind.",
    "How you're the one I can't live without.",
    "The way you never make me feel like I'm not enough.",
    "Your ability to make me feel like more than enough.",
    "The way you always find a way to appreciate me.",
    "How you're my favorite thing about life.",
    "Your ability to make me feel like a blessing.",
    "The way you always find a way to support me.",
    "How you're my favorite person to support.",
    "The way you never make me feel like I'm wrong for being me.",
    "Your ability to make me feel right for being me.",
    "The way you always find a way to celebrate me.",
    "How you're my favorite person to celebrate.",
    "The way you never make me feel like I'm lost.",
    "Your ability to make me feel found.",
    "The way you always find a way to guide me.",
    "How you're my favorite guide.",
    "The way you never make me feel like I'm a secret.",
    "Your ability to make me feel like a truth.",
    "The way you always find a way to share with me.",
    "How you're my favorite person to share with.",
    "The way you never make me feel like I'm a shadow.",
    "Your ability to make me feel like a light.",
    "The way you always find a way to shine with me.",
    "How you're my favorite person to shine with.",
    "The way you never make me feel like I'm an echo.",
    "Your ability to make me feel like a voice.",
    "The way you always find a way to speak with me.",
    "How you're my favorite person to speak with.",
    "The way you never make me feel like I'm a ghost.",
    "Your ability to make me feel so real.",
    "The way you always find a way to live with me.",
    "How you're my favorite person to live for.",
    "The way you never make me feel like I'm a memory.",
    "Your ability to make me feel like a future.",
    "The way you always find a way to dream with me.",
    "How you're my favorite person to dream with.",
    "The way you never make me feel like I'm a stranger.",
    "Your ability to make me feel like family.",
    "The way you always find a way to belong with me.",
    "How you're my favorite person to belong to.",
    "The way you never make me feel like I'm a question.",
    "Your ability to make me feel like an answer.",
    "The way you always find a way to know me.",
    "How you're my favorite person to know.",
    "The way you never make me feel like I'm a part.",
    "Your ability to make me feel like a whole.",
    "The way you always find a way to complete me.",
    "How you're my favorite person to complete.",
    "The way you never make me feel like I'm a burden. (Again, because it's true!)",
    "Your ability to make me feel like a gift.",
    "The way you always find a way to give to me.",
    "How you're my favorite person to give to.",
    "The way you never make me feel like I'm a chore.",
    "Your ability to make me feel like a pleasure.",
    "The way you always find a way to enjoy me.",
    "How you're my favorite person to enjoy life with.",
    "The way you never make me feel like I'm a risk.",
    "Your ability to make me feel like a sure thing.",
    "The way you always find a way to trust me.",
    "How you're my favorite person to trust.",
    "The way you never make me feel like I'm a regret.",
    "Your ability to make me feel like a pride.",
    "The way you always find a way to be proud of me.",
    "How you're my favorite person to be proud of.",
    "Your ability to make me feel like a miracle.",
    "The way you always find a way to wonder at me.",
    "How you're my favorite wonder in the world.",
    "The way you never make me feel like I'm a trial.",
    "Your ability to make me feel like a victory.",
    "The way you always find a way to win with me.",
    "How you're my favorite person to win with.",
    "The way you never make me feel like I'm a loss.",
    "Your ability to make me feel like a find.",
    "The way you always find a way to find me.",
    "How you're my favorite person to find.",
    "Your ability to make me feel so solid.",
    "The way you always find a way to hold me.",
    "How you're my favorite person to hold onto.",
    "Your ability to make me feel so bright.",
    "The way you always find a way to light me up.",
    "How you're my favorite person to light up with.",
    "Your ability to make me feel so known.",
    "The way you always find a way to show me off.",
    "How you're my favorite person to show off.",
    "The way you always find a way to bless me.",
    "How you're my favorite person to bless.",
    "Your ability to make me feel like a delight.",
    "The way you always find a way to delight in me.",
    "How you're my favorite person to delight in.",
    "Your ability to make me feel like a joy.",
    "The way you always find a way to joy in me.",
    "How you're my favorite person to joy with.",
    "The way you never make me feel like I'm a task.",
    "Your ability to make me feel like a treasure.",
    "The way you always find a way to treasure me.",
    "How you're my favorite person to treasure.",
    "The way you never make me feel like I'm a tool.",
    "Your ability to make me feel like a partner.",
    "The way you always find a way to partner with me.",
    "How you're my favorite person to partner with.",
    "The way you never make me feel like I'm a used.",
    "Your ability to make me feel like a loved.",
    "The way you always find a way to love me.",
    "How you're my favorite person to love.",
    "The way you never make me feel like I'm a fool.",
    "Your ability to make me feel like a genius.",
    "The way you always find a way to think with me.",
    "How you're my favorite person to think with.",
    "The way you never make me feel like I'm a slow.",
    "Your ability to make me feel like a fast.",
    "The way you always find a way to run with me.",
    "How you're my favorite person to run with.",
    "The way you never make me feel like I'm a stop.",
    "Your ability to make me feel like a go.",
    "The way you always find a way to go with me.",
    "How you're my favorite person to go with.",
    "The way you never make me feel like I'm a end.",
    "Your ability to make me feel like a beginning.",
    "The way you always find a way to start with me.",
    "How you're my favorite person to start with.",
    "The way you never make me feel like I'm a old.",
    "Your ability to make me feel like a new.",
    "The way you always find a way to be new with me.",
    "How you're my favorite person to be new with.",
    "The way you never make me feel like I'm a boring.",
    "Your ability to make me feel like a fun.",
    "The way you always find a way to have fun with me.",
    "How you're my favorite person to have fun with.",
    "The way you never make me feel like I'm a sad.",
    "Your ability to make me feel like a happy.",
    "The way you always find a way to be happy with me.",
    "How you're my favorite person to be happy with.",
    "The way you never make me feel like I'm a alone.",
    "Your ability to make me feel like a together.",
    "The way you always find a way to be together with me.",
    "How you're my favorite person to be together with.",
    "The way you never make me feel like I'm a apart.",
    "Your ability to make me feel like a heart.",
    "The way you always find a way to be in my heart.",
    "How you're my favorite heart.",
    "The way you never make me feel like I'm a away.",
    "Your ability to make me feel like a here.",
    "The way you always find a way to be here with me.",
    "How you're my favorite here.",
    "The way you never make me feel like I'm a then.",
    "Your ability to make me feel like a now.",
    "The way you always find a way to be now with me.",
    "How you're my favorite now.",
    "The way you never make me feel like I'm a maybe.",
    "Your ability to make me feel like a yes.",
    "The way you always find a way to say yes to me.",
    "How you're my favorite yes.",
    "The way you never make me feel like I'm a no.",
    "Your ability to make me feel like a all.",
    "The way you always find a way to be all with me.",
    "How you're my favorite all.",
    "The way you never make me feel like I'm a some.",
    "Your ability to make me feel like a every.",
    "The way you always find a way to be every with me.",
    "How you're my favorite every.",
    "The way you always find a way to be whole with me.",
    "How you're my favorite whole.",
    "The way you never make me feel like I'm a pieces.",
    "Your ability to make me feel like a solid.",
    "The way you always find a way to be solid with me.",
    "How you're my favorite solid.",
    "The way you never make me feel like I'm a weak.",
    "Your ability to make me feel like a strong.",
    "The way you always find a way to be strong with me.",
    "How you're my favorite strong.",
    "The way you never make me feel like I'm a down.",
    "Your ability to make me feel like a up.",
    "The way you always find a way to be up with me.",
    "How you're my favorite up.",
    "The way you never make me feel like I'm a low.",
    "Your ability to make me feel like a high.",
    "The way you always find a way to be high with me.",
    "How you're my favorite high.",
    "The way you never make me feel like I'm a dark.",
    "The way you always find a way to be light with me.",
    "How you're my favorite light.",
    "The way you never make me feel like I'm a cold.",
    "Your ability to make me feel like a warm.",
    "The way you always find a way to be warm with me.",
    "How you're my favorite warm.",
    "The way you never make me feel like I'm a empty.",
    "Your ability to make me feel like a full.",
    "The way you always find a way to be full with me.",
    "How you're my favorite full.",
    "The way you never make me feel like I'm a less.",
    "Your ability to make me feel like a more.",
    "The way you always find a way to be more with me.",
    "How you're my favorite more.",
    "The way you never make me feel like I'm a none.",
    "Your ability to make me feel like a one.",
    "The way you always find a way to be one with me.",
    "How you're my favorite one.",
    "The way you never make me feel like I'm a zero.",
    "Your ability to make me feel like a hero.",
    "The way you always find a way to be my hero.",
    "How you're my favorite hero.",
    "The way you never make me feel like I'm a side.",
    "Your ability to make me feel like a front.",
    "The way you always find a way to be in front with me.",
    "How you're my favorite front.",
    "The way you never make me feel like I'm a back.",
    "Your ability to make me feel like a first.",
    "The way you always find a way to be first with me.",
    "How you're my favorite first.",
    "The way you never make me feel like I'm a last.",
    "Your ability to make me feel like a only.",
    "The way you always find a way to be my only.",
    "How you're my favorite only.",
    "The way you never make me feel like I'm a other.",
    "Your ability to make me feel like a same.",
    "The way you always find a way to be the same with me.",
    "How you're my favorite same.",
    "The way you never make me feel like I'm a different.",
    "Your ability to make me feel like a soul.",
    "The way you always find a way to be my soul.",
    "How you're my favorite soul.",
    "The way you never make me feel like I'm a body.",
    "Your ability to make me feel like a spirit.",
    "The way you always find a way to be my spirit.",
    "How you're my favorite spirit.",
    "The way you never make me feel like I'm a earth.",
    "Your ability to make me feel like a sky.",
    "The way you always find a way to be my sky.",
    "How you're my favorite sky.",
    "The way you never make me feel like I'm a sea.",
    "Your ability to make me feel like a sun.",
    "The way you always find a way to be my sun.",
    "How you're my favorite sun.",
    "The way you never make me feel like I'm a moon.",
    "Your ability to make me feel like a star.",
    "The way you always find a way to be my star.",
    "How you're my favorite star.",
    "The way you never make me feel like I'm a cloud.",
    "Your ability to make me feel like a rain.",
    "The way you always find a way to be my rain.",
    "How you're my favorite rain.",
    "The way you never make me feel like I'm a storm.",
    "Your ability to make me feel like a rainbow.",
    "The way you always find a way to be my rainbow.",
    "How you're my favorite rainbow.",
    "The way you never make me feel like I'm a wind.",
    "Your ability to make me feel like a fire.",
    "The way you always find a way to be my fire.",
    "How you're my favorite fire.",
    "The way you never make me feel like I'm a ice.",
    "Your ability to make me feel like a burn. (The good kind!)",
    "The way you always find a way to burn with me.",
    "How you're my favorite burn.",
    "The way you never make me feel like I'm a ash.",
    "Your ability to make me feel like a spark.",
    "The way you always find a way to spark with me.",
    "How you're my favorite spark.",
    "The way you never make me feel like I'm a dust.",
    "Your ability to make me feel like a gem.",
    "The way you always find a way to be my gem.",
    "How you're my favorite gem.",
    "The way you never make me feel like I'm a rock.",
    "Your ability to make me feel like a gold.",
    "The way you always find a way to be my gold.",
    "How you're my favorite gold.",
    "The way you never make me feel like I'm a silver.",
    "Your ability to make me feel like a diamond.",
    "The way you always find a way to be my diamond.",
    "How you're my favorite diamond.",
    "The way you never make me feel like I'm a copper.",
    "Your ability to make me feel like a steel.",
    "The way you always find a way to be my steel.",
    "How you're my favorite steel.",
    "The way you never make me feel like I'm a glass.",
    "Your ability to make me feel like a unbreakable.",
    "The way you always find a way to be unbreakable with me.",
    "How you're my favorite unbreakable.",
    "The way you never make me feel like I'm a wood.",
    "Your ability to make me feel like a leaf.",
    "The way you always find a way to be my leaf.",
    "How you're my favorite leaf.",
    "The way you never make me feel like I'm a root.",
    "Your ability to make me feel like a tree.",
    "The way you always find a way to be my tree.",
    "How you're my favorite tree.",
    "The way you never make me feel like I'm a flower.",
    "Your ability to make me feel like a garden.",
    "The way you always find a way to be my garden.",
    "How you're my favorite garden.",
    "The way you never make me feel like I'm a seed.",
    "Your ability to make me feel like a fruit.",
    "The way you always find a way to be my fruit.",
    "How you're my favorite fruit.",
    "The way you never make me feel like I'm a winter.",
    "Your ability to make me feel like a spring.",
    "The way you always find a way to be my spring.",
    "How you're my favorite spring.",
    "The way you never make me feel like I'm a summer.",
    "Your ability to make me feel like a autumn.",
    "The way you always find a way to be my autumn.",
    "How you're my favorite autumn.",
    "The way you never make me feel like I'm a day.",
    "Your ability to make me feel like a night.",
    "The way you always find a way to be my night.",
    "How you're my favorite night.",
    "The way you never make me feel like I'm a second.",
    "Your ability to make me feel like a hour.",
    "The way you always find a way to be my hour.",
    "How you're my favorite hour.",
    "The way you never make me feel like I'm a week.",
    "Your ability to make me feel like a month.",
    "The way you always find a way to be my month.",
    "How you're my favorite month.",
    "The way you never make me feel like I'm a year.",
    "Your ability to make me feel like a lifetime.",
    "The way you always find a way to be my lifetime.",
    "How you're my favorite lifetime.",
    "The way you never make me feel like I'm a moment.",
    "Your ability to make me feel like a eternity.",
    "The way you always find a way to be my eternity.",
    "How you're my favorite eternity.",
    "The way you never make me feel like I'm a step.",
    "Your ability to make me feel like a path.",
    "The way you always find a way to be my path.",
    "How you're my favorite path.",
    "The way you never make me feel like I'm a road.",
    "Your ability to make me feel like a destination.",
    "The way you always find a way to be my destination.",
    "How you're my favorite destination.",
    "Your ability to make me feel like a infinity.",
    "The way you always find a way to be my infinity.",
    "How you're my favorite infinity.",
    "The way you never make me feel like I'm a point.",
    "Your ability to make me feel like a line.",
    "The way you always find a way to be my line.",
    "How you're my favorite line.",
    "The way you never make me feel like I'm a circle.",
    "Your ability to make me feel like a sphere.",
    "The way you always find a way to be my sphere.",
    "How you're my favorite sphere.",
    "The way you never make me feel like I'm a edge.",
    "Your ability to make me feel like a center.",
    "The way you always find a way to be my center.",
    "How you're my favorite center.",
    "The way you never make me feel like I'm a top.",
    "Your ability to make me feel like a bottom. (Again, hold!)",
    "The way you always find a way to be my everything.",
    "How you're my favorite everything.",
    "The way you never make me feel like I'm a not.",
    "Your ability to make me feel like a be.",
    "The way you always find a way to be with me.",
    "How you're my favorite be.",
    "The way you never make me feel like I'm a was.",
    "Your ability to make me feel like a is.",
    "The way you always find a way to is with me.",
    "How you're my favorite is.",
    "The way you never make me feel like I'm a will.",
    "Your ability to make me feel like a am.",
    "The way you always find a way to be am with me.",
    "How you're my favorite am.",
    "The way you never make me feel like I'm a me.",
    "Your ability to make me feel like a you.",
    "The way you always find a way to be you with me.",
    "How you're my favorite you.",
    "The way you never make me feel like I'm a us.",
    "Your ability to make me feel like a we.",
    "The way you always find a way to be we with me.",
    "How you're my favorite we.",
    "The way you never make me feel like I'm a them.",
    "Your ability to make me feel like a our.",
    "The way you always find a way to be our with me.",
    "How you're my favorite our.",
    "The way you never make me feel like I'm a they.",
    "Your ability to make me feel like a mine.",
    "The way you always find a way to be mine with me.",
    "How you're my favorite mine.",
    "The way you never make me feel like I'm a yours.",
    "Your ability to make me feel like a own.",
    "The way you always find a way to be my own.",
    "How you're my favorite own.",
    "The way you never make me feel like I'm a self.",
    "Your ability to make me feel like a soul. (Soul again!)",
    "The way you never make me feel like I'm a alone. (Final one!)",
    "Your ability to make me feel so together.",
    "The way you always find a way to be here, always.",
    "How you're my favorite person, forever and always."
];

function showReasons() {
    closeMessage();
    const letterCard = document.querySelector('.letter-card');
    const reasonsSection = document.getElementById('reasons-section');
    const reasonsList = document.getElementById('reasons-list');
    const countDisplay = document.getElementById('reasons-count');

    letterCard.style.display = 'none';
    reasonsSection.style.display = 'flex';
    reasonsList.innerHTML = '';

    // Animate counter
    let count = 0;
    const duration = 2000; // 2 seconds
    const startTime = performance.now();

    createHearts(); // Add some magic ✨

    function updateCounter(currentTime) {
        const elapsed = currentTime - startTime;
        const progress = Math.min(elapsed / duration, 1);

        // Easing function
        const easeOutQuad = t => t * (2 - t);
        const currentCount = Math.floor(easeOutQuad(progress) * reasons.length);

        countDisplay.textContent = currentCount;

        if (progress < 1) {
            requestAnimationFrame(updateCounter);
        } else {
            countDisplay.textContent = reasons.length;
            renderReasons();
        }
    }

    requestAnimationFrame(updateCounter);
}

function renderReasons() {
    const reasonsList = document.getElementById('reasons-list');
    reasonsList.innerHTML = ''; // Ensure it's clean

    reasons.forEach((reason, index) => {
        setTimeout(() => {
            const item = document.createElement('div');
            item.className = 'reason-item';
            item.innerHTML = `
                <div class="reason-num">${index + 1}</div>
                <div class="reason-text">${reason}</div>
            `;
            reasonsList.appendChild(item);

            // Fast trigger to show and scroll
            setTimeout(() => {
                item.classList.add('visible');
                reasonsList.scrollTop = reasonsList.scrollHeight; // Simpler scroll
            }, 50);
        }, index * 25); // Fast staggered appearance
    });
}

function backToLetter() {
    const letterCard = document.querySelector('.letter-card');
    const reasonsSection = document.getElementById('reasons-section');
    reasonsSection.style.display = 'none';
    letterCard.style.display = 'block';
}

// Happiness & Game Logic
function showHappiness() {
    document.getElementById('reasons-section').style.display = 'none';
    document.getElementById('happiness-section').style.display = 'block';
    createHearts();
}

function backToHappiness() {
    document.getElementById('game-section').style.display = 'none';
    document.getElementById('happiness-section').style.display = 'block';
}

function showGame() {
    document.getElementById('happiness-section').style.display = 'none';
    document.getElementById('game-section').style.display = 'flex';
    resetGame();
}

let score = 0;
const gameHeart = document.getElementById('game-heart');
const scoreDisplay = document.getElementById('game-score');
const gameArea = document.getElementById('game-area');

gameHeart.addEventListener('click', () => {
    score++;
    scoreDisplay.textContent = score;
    createHearts(); // Bonus hearts on click!

    if (score >= 5) {
        alert("Yay! You caught my heart! ❤️ Now you HAVE to forgive me and we HAVE to meet soon! No excuses allowed! 😤✨");
        score = 0;
        scoreDisplay.textContent = score;
        backToLetter(); // Go back or to a final celebration? Let's go back to letter for now.
    } else {
        moveHeart();
    }
});

function moveHeart() {
    const maxX = gameArea.clientWidth - gameHeart.clientWidth - 20;
    const maxY = gameArea.clientHeight - gameHeart.clientHeight - 20;

    const x = Math.max(10, Math.random() * maxX);
    const y = Math.max(10, Math.random() * maxY);

    gameHeart.style.left = `${x}px`;
    gameHeart.style.top = `${y}px`;
}

function resetGame() {
    score = 0;
    scoreDisplay.textContent = score;
    moveHeart();
}

// Auto-move heart if they are too slow (to make it funny)
setInterval(() => {
    if (document.getElementById('game-section').style.display === 'flex' && score < 5) {
        moveHeart();
    }
}, 1500);

function createHearts() {
    for (let i = 0; i < 30; i++) {
        const heart = document.createElement('div');
        const hearts = ['💖', '💗', '✨', '🌸', '🤍'];
        heart.innerHTML = hearts[Math.floor(Math.random() * hearts.length)];
        heart.classList.add('heart-animation');
        heart.style.left = Math.random() * 100 + 'vw';
        heart.style.top = '100vh';
        heart.style.fontSize = Math.random() * 20 + 15 + 'px';
        heart.style.animation = `flyAway ${Math.random() * 2 + 3}s linear forwards`;
        document.body.appendChild(heart);

        // Remove heart after animation
        setTimeout(() => {
            heart.remove();
        }, 5000);
    }
}
